# Generated by Django 3.2.5 on 2022-08-11 00:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('-published',)},
        ),
        migrations.AddField(
            model_name='noticia',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(default='noticiaNoEncontrada', max_length=250, unique=True, unique_for_date='published'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('texto', models.TextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='noticia.noticia')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
