# Generated by Django 3.2.5 on 2022-08-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_auto_20220731_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='texto',
        ),
    ]
