# Generated by Django 3.2.5 on 2022-08-09 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticia', '0003_remove_noticia_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticia',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticia',
            name='texto',
            field=models.TextField(default='Hola mundo'),
            preserve_default=False,
        ),
    ]
