# Generated by Django 3.2.5 on 2022-08-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_auto_20220811_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.TextField(blank=True, max_length=90, null=True),
        ),
    ]
