# Generated by Django 3.2.5 on 2022-08-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_auto_20220809_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='slug',
        ),
    ]
