# Generated by Django 3.2.5 on 2022-08-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_auto_20220814_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
