# Generated by Django 3.2.5 on 2022-08-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0006_alter_noticia_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='noticia/default.png', null=True, upload_to='noticia'),
        ),
    ]
