# Generated by Django 3.2.5 on 2022-08-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_comentarios_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='object_id',
        ),
    ]
