# Generated by Django 3.2.5 on 2022-08-23 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentario', '0003_auto_20220814_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
