# Generated by Django 3.2.5 on 2022-08-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0004_auto_20220823_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='user',
            new_name='usuario',
        ),
    ]
